apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trendscout.fullname" . }}-redis
  labels:
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
              name: redis
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 10
