/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuthSignUpRouteImport } from "./routes/_auth/sign-up"
import { Route as AuthSignInRouteImport } from "./routes/_auth/sign-in"
import { Route as AuthForgotPasswordRouteImport } from "./routes/_auth/forgot-password"
import { Route as AppSettingsRouteImport } from "./routes/_app/settings"
import { Route as AppHealthRouteImport } from "./routes/_app/health"
import { Route as AppExampleRouteImport } from "./routes/_app/example"
import { Route as AppDashboardRouteImport } from "./routes/_app/dashboard"
import { Route as AppSettingsIndexRouteImport } from "./routes/_app/settings/index"
import { Route as AppSettingsNotificationsRouteImport } from "./routes/_app/settings/notifications"
import { Route as AppSettingsDisplayRouteImport } from "./routes/_app/settings/display"
import { Route as AppSettingsAppearanceRouteImport } from "./routes/_app/settings/appearance"
import { Route as AppSettingsAccountRouteImport } from "./routes/_app/settings/account"

const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: "/health",
  path: "/health",
  getParentRoute: () => AppRoute,
} as any)
const AppExampleRoute = AppExampleRouteImport.update({
  id: "/example",
  path: "/example",
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsDisplayRoute = AppSettingsDisplayRouteImport.update({
  id: "/display",
  path: "/display",
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: "/appearance",
  path: "/appearance",
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/dashboard": typeof AppDashboardRoute
  "/example": typeof AppExampleRoute
  "/health": typeof AppHealthRoute
  "/settings": typeof AppSettingsRouteWithChildren
  "/forgot-password": typeof AuthForgotPasswordRoute
  "/sign-in": typeof AuthSignInRoute
  "/sign-up": typeof AuthSignUpRoute
  "/settings/account": typeof AppSettingsAccountRoute
  "/settings/appearance": typeof AppSettingsAppearanceRoute
  "/settings/display": typeof AppSettingsDisplayRoute
  "/settings/notifications": typeof AppSettingsNotificationsRoute
  "/settings/": typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/dashboard": typeof AppDashboardRoute
  "/example": typeof AppExampleRoute
  "/health": typeof AppHealthRoute
  "/forgot-password": typeof AuthForgotPasswordRoute
  "/sign-in": typeof AuthSignInRoute
  "/sign-up": typeof AuthSignUpRoute
  "/settings/account": typeof AppSettingsAccountRoute
  "/settings/appearance": typeof AppSettingsAppearanceRoute
  "/settings/display": typeof AppSettingsDisplayRoute
  "/settings/notifications": typeof AppSettingsNotificationsRoute
  "/settings": typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_app": typeof AppRouteWithChildren
  "/_auth": typeof AuthRouteWithChildren
  "/_app/dashboard": typeof AppDashboardRoute
  "/_app/example": typeof AppExampleRoute
  "/_app/health": typeof AppHealthRoute
  "/_app/settings": typeof AppSettingsRouteWithChildren
  "/_auth/forgot-password": typeof AuthForgotPasswordRoute
  "/_auth/sign-in": typeof AuthSignInRoute
  "/_auth/sign-up": typeof AuthSignUpRoute
  "/_app/settings/account": typeof AppSettingsAccountRoute
  "/_app/settings/appearance": typeof AppSettingsAppearanceRoute
  "/_app/settings/display": typeof AppSettingsDisplayRoute
  "/_app/settings/notifications": typeof AppSettingsNotificationsRoute
  "/_app/settings/": typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/dashboard"
    | "/example"
    | "/health"
    | "/settings"
    | "/forgot-password"
    | "/sign-in"
    | "/sign-up"
    | "/settings/account"
    | "/settings/appearance"
    | "/settings/display"
    | "/settings/notifications"
    | "/settings/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/dashboard"
    | "/example"
    | "/health"
    | "/forgot-password"
    | "/sign-in"
    | "/sign-up"
    | "/settings/account"
    | "/settings/appearance"
    | "/settings/display"
    | "/settings/notifications"
    | "/settings"
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/_auth"
    | "/_app/dashboard"
    | "/_app/example"
    | "/_app/health"
    | "/_app/settings"
    | "/_auth/forgot-password"
    | "/_auth/sign-in"
    | "/_auth/sign-up"
    | "/_app/settings/account"
    | "/_app/settings/appearance"
    | "/_app/settings/display"
    | "/_app/settings/notifications"
    | "/_app/settings/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/sign-up": {
      id: "/_auth/sign-up"
      path: "/sign-up"
      fullPath: "/sign-up"
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/sign-in": {
      id: "/_auth/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/forgot-password": {
      id: "/_auth/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_app/settings": {
      id: "/_app/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/health": {
      id: "/_app/health"
      path: "/health"
      fullPath: "/health"
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/example": {
      id: "/_app/example"
      path: "/example"
      fullPath: "/example"
      preLoaderRoute: typeof AppExampleRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/dashboard": {
      id: "/_app/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/settings/": {
      id: "/_app/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    "/_app/settings/notifications": {
      id: "/_app/settings/notifications"
      path: "/notifications"
      fullPath: "/settings/notifications"
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    "/_app/settings/display": {
      id: "/_app/settings/display"
      path: "/display"
      fullPath: "/settings/display"
      preLoaderRoute: typeof AppSettingsDisplayRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    "/_app/settings/appearance": {
      id: "/_app/settings/appearance"
      path: "/appearance"
      fullPath: "/settings/appearance"
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    "/_app/settings/account": {
      id: "/_app/settings/account"
      path: "/account"
      fullPath: "/settings/account"
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsDisplayRoute: typeof AppSettingsDisplayRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsDisplayRoute: AppSettingsDisplayRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExampleRoute: typeof AppExampleRoute
  AppHealthRoute: typeof AppHealthRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExampleRoute: AppExampleRoute,
  AppHealthRoute: AppHealthRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
