apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trendscout.fullname" . }}-postgres
  labels:
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  password: {{ .Values.password | quote }}
