apiVersion: v1
kind: Service
metadata:
  name: {{ include "trendscout.fullname" . }}-postgres
  labels:
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/component: postgres
